### ISSUE TITLE
Cannot login using guest account on DeltaBreed website

### ISSUE THREAD

**Issue by jeekinlau** [Breeding-Insight/bi-web#379]
The only option to login on DeltaBreed sandbox is using orcid. There is no input box for user and password. Attached is a screenshot.

![image](https://github.com/Breeding-Insight/bi-web/assets/77897366/b9d6fec9-71e7-4919-9cdd-30622c103060)

**Comment by nickpalladino** [comment]
Hi @jeekinlau, thanks for checking out the sandbox! If you click the Sign In with ORCID button you will be redirected to an ORCID sandbox login page which will have a form to enter the username and password listed on menu bar. Apologies for the delay, if you have any further issues let us know.
